// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2oePPTOs-tzSdn_IFK3qiHI6frDzdJYc',
    appId: '1:652184434195:web:5f75914d9b202e4338f1e6',
    messagingSenderId: '652184434195',
    projectId: 'chat-application-63822',
    authDomain: 'chat-application-63822.firebaseapp.com',
    storageBucket: 'chat-application-63822.appspot.com',
    measurementId: 'G-J9J1V71PKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzNMHSjdxYuYoEf_sWoPOIr3P3Ym7bJ-s',
    appId: '1:652184434195:android:c7c74a5a3022211738f1e6',
    messagingSenderId: '652184434195',
    projectId: 'chat-application-63822',
    storageBucket: 'chat-application-63822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbOsS3Z9utudZZF2jwgDA1r1jxA_AK6PE',
    appId: '1:652184434195:ios:a0bd05fd249288c838f1e6',
    messagingSenderId: '652184434195',
    projectId: 'chat-application-63822',
    storageBucket: 'chat-application-63822.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbOsS3Z9utudZZF2jwgDA1r1jxA_AK6PE',
    appId: '1:652184434195:ios:5bc17ecd74e8bbfe38f1e6',
    messagingSenderId: '652184434195',
    projectId: 'chat-application-63822',
    storageBucket: 'chat-application-63822.appspot.com',
    iosBundleId: 'com.example.chatApplication.RunnerTests',
  );
}
